apiVersion: v1
kind: Template
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${REDIS_SERVICE_PREFIX}-redis-slave
    name: ${REDIS_SERVICE_PREFIX}-redis-slave
  spec:
    replicas: 2
    selector:
      app: ${REDIS_SERVICE_PREFIX}-redis-slave
    template:
      metadata:
        labels:
          app: ${REDIS_SERVICE_PREFIX}-redis-slave
      spec:
        containers:
        - env:
            - name: REDIS_DATA_MAX_AGE
              value: ${REDIS_DATA_MAX_AGE}
            - name: REDIS_SENTINEL_SERVICE_HOST
              value: ${REDIS_SERVICE_PREFIX}-redis-sentinel
            - name: REDIS_SENTINEL_SERVICE_PORT
              value: ${REDIS_SENTINEL_SERVICE_PORT}
            - name: REDIS_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_NAMESPACE
              value: ktaxa-solution-delivery-sandbox-dev
          image: ${REDIS_IMAGE}
          imagePullPolicy: Always
          name: ${REDIS_SERVICE_PREFIX}-redis-slave
          ports:
            - containerPort: 6379
          resources: {}
        - image: ${REDIS_IMAGE}    
          imagePullPolicy: Always
          name: ${REDIS_SERVICE_PREFIX}-sentinel
          resources: {}
          ports:
            - containerPort: 26379
          env:
            - name: SENTINEL
              value: "true"
            - name: REDIS_DATA_MAX_AGE
              value: ${REDIS_DATA_MAX_AGE}
            - name: REDIS_SENTINEL_SERVICE_HOST
              value: ${REDIS_SERVICE_PREFIX}-redis-sentinel
            - name: REDIS_SENTINEL_SERVICE_PORT
              value: ${REDIS_SENTINEL_SERVICE_PORT}
            - name: REDIS_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_NAMESPACE
              value: ktaxa-solution-delivery-sandbox-dev  
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30  
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30

    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${REDIS_SERVICE_PREFIX}-redis-slave
        - ${REDIS_SERVICE_PREFIX}-sentinel
        from:
          kind: ImageStreamTag
          name: ${REDIS_IMAGE}
      type: ImageChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${REDIS_SERVICE_PREFIX}-redis-slave
    name: ${REDIS_SERVICE_PREFIX}-redis-slave
  spec:
    ports:
      - port: 6379
        targetPort: 6379
    selector:
      app: ${REDIS_SERVICE_PREFIX}-redis-slave

parameters:
- name: REDIS_SERVICE_PREFIX                                                                            
  description: Name of the redis service. It is used as the prefix for all components.                  
  required: true                                                                                        
- name: REDIS_IMAGE                                                                            
  description: Location and name of the Redis Sentinel image.                                           
  required: true                                                                                                                                                                             
- name: REDIS_DATA_MAX_AGE                                                                            
  description: Maximal age of slave data directories in days.
  required: true
  value: "4"
- name: REDIS_SENTINEL_SERVICE_PORT
  description: Port of the redis sentinel service
  required: true
  value: "26379"
